package capability

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Shared cross-language test vectors. These are generated by
// origin/cmd/gentestvectors and committed under docs/test-vectors/.
// Both this Go test and the Python test consume the same file. If either
// implementation drifts from the spec, this test fails.
//
// Vectors file lives relative to the repo root. The test walks up from
// the package dir until it finds docs/test-vectors/capability.json.

type vectorBundle struct {
	Vectors []struct {
		Name               string `json:"name"`
		PublicKeyBase64    string `json:"public_key_b64"`
		PrivateKeyBase64   string `json:"private_key_b64"`
		Capability         struct {
			Code   string `json:"code"`
			Scope  string `json:"scope"`
			Signer string `json:"signer"`
			Exp    int64  `json:"exp"`
			Uses   int64  `json:"uses"`
			Nonce  string `json:"nonce"`
		} `json:"capability"`
		ExpectedToken string `json:"expected_token"`
	} `json:"vectors"`
}

func TestCrossLanguageVectors(t *testing.T) {
	path := findVectorsFile(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var bundle vectorBundle
	if err := json.Unmarshal(raw, &bundle); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(bundle.Vectors) == 0 {
		t.Fatal("no vectors found")
	}

	for _, vec := range bundle.Vectors {
		t.Run(vec.Name, func(t *testing.T) {
			priv, err := base64.RawURLEncoding.DecodeString(vec.PrivateKeyBase64)
			if err != nil {
				t.Fatalf("decode private key: %v", err)
			}
			pub, err := base64.RawURLEncoding.DecodeString(vec.PublicKeyBase64)
			if err != nil {
				t.Fatalf("decode public key: %v", err)
			}

			// 1. Re-sign the capability. Must match the recorded token byte-for-byte.
			cap := &Capability{
				Code:   vec.Capability.Code,
				Scope:  vec.Capability.Scope,
				Signer: vec.Capability.Signer,
				Exp:    vec.Capability.Exp,
				Uses:   vec.Capability.Uses,
				Nonce:  vec.Capability.Nonce,
			}
			reproduced, err := cap.Sign(ed25519.PrivateKey(priv))
			if err != nil {
				t.Fatalf("sign: %v", err)
			}
			if reproduced != vec.ExpectedToken {
				t.Errorf("re-sign mismatch\n  want: %s\n  got:  %s", vec.ExpectedToken, reproduced)
			}

			// 2. Verify the recorded token with the recorded public key.
			//    Use now=0 so expired fixtures don't fail — we test expiry
			//    separately in capability_test.go.
			got, err := Verify(vec.ExpectedToken, ed25519.PublicKey(pub), time.Time{})
			if err != nil {
				t.Fatalf("verify: %v", err)
			}
			if got.Code != cap.Code || got.Scope != cap.Scope ||
				got.Signer != cap.Signer || got.Exp != cap.Exp ||
				got.Uses != cap.Uses || got.Nonce != cap.Nonce {
				t.Errorf("round-trip body mismatch\n  want: %+v\n  got:  %+v", cap, got)
			}
		})
	}
}

// findVectorsFile walks up from CWD until it finds docs/test-vectors/capability.json.
// Lets this test run from any working directory under the repo.
func findVectorsFile(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	dir := wd
	for i := 0; i < 10; i++ {
		candidate := filepath.Join(dir, "docs", "test-vectors", "capability.json")
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Skipf("docs/test-vectors/capability.json not found (walked up from %s); run `go run ./origin/cmd/gentestvectors > docs/test-vectors/capability.json` first", strings.TrimSpace(wd))
	return ""
}
